---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
  index.html: |
    <h1 style='color: {{ pluck .Values.env .Values.color | first | default .Values.color._default }};'>
    Hello world!
    </h1>
